In [3]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Review

## Discussion Question 1

The past weeks temperatures in Fahrenheit were:
70, 68, 66, 71, 72, 70, 68

The connection between Fahrenheit temperature F and Celsius temperature C is:
C = 5/9(F - 32)

Use an array calculation to convert all these Fahrenheit temperatures to Celsius.

In [4]:
fahrenheit_temps = make_array(70, 68, 66, 71, 72, 70, 68)
celsius_temps = 5 / 9 * fahrenheit_temps
celsius_temps

array([ 38.88888889,  37.77777778,  36.66666667,  39.44444444,
        40.        ,  38.88888889,  37.77777778])

In [5]:
# Bonus: Round them all to one decimal place
celsius_temps = np.round(celsius_temps, 1)
celsius_temps

array([ 38.9,  37.8,  36.7,  39.4,  40. ,  38.9,  37.8])

## Discussion Question 2

A lemonade stand sold
- 50 cups of lemonade at $3.50 each
- 35 bottles of water at $2.00 each
- 25 cookies at $3.00 each

Create an array for sales and an array for cost. Use these to produce a third array for revenue generated by each item (lemonade revenue in the first entry, water revenue in the second, and cookie revenue in the third).

In [6]:
sales = make_array(50, 35, 25)
cost = make_array(3.50, 2.00, 3.00)
revenue = sales * cost
revenue

array([ 175.,   70.,   75.])

In [7]:
# Bonus: The total revenue is
np.sum(revenue)

320.0

# Ranges

In [8]:
# One argument gives an array from 0 to the integer provided (excluding right endpoint)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Two arguments denotes the starting value (inclusive) and ending value (exclusive)
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [10]:
# Three arguments denotes the starting value, ending value, and step size
np.arange(5, 10, 2)

array([5, 7, 9])

# Functions on Arrays (textbook 5.1)

In [11]:
nums = np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [12]:
np.sum(nums)

10

In [13]:
np.diff(nums)

array([1, 1, 1, 1])

In [14]:
np.mean(nums)

2.0

# Practice

1. Use arange to generate the following approximation of $\pi$:

$$4 \cdot \left( \left(1 + \frac{1}{5} + \frac{1}{9} + \dots + \frac{1}{9997} \right) - \left(\frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \dots + \frac{1}{9999} \right) \right)$$

- Use arange to generate an array containing 1, 5, 9, ... , 9997
- Use / to generate an array containing 1/1, 1/5, 1/9, ..., 1/9997
- Sum the elements of this array to get the value of the first parenthesis
- Go through a similar process to get the second parenthesis
- Calculuate the estimate

2. Use arange to generate the following approximation of $\pi$:
$$2 \cdot \left( \frac{2}{1} \cdot \frac{4}{3} \cdot \frac{6}{5} \cdots \frac{1,000,000}{999999} \right) \cdot \left( \frac{2}{3} \cdot \frac{4}{5} \cdot \frac{6}{7} \cdots \frac{1,000,000}{1,000,001} \right)$$

In [15]:
pie_array = np.arange(1,9997,4)
pie_array

array([   1,    5,    9, ..., 9985, 9989, 9993])

In [16]:
P_array = 1/pie_array
P_array

array([  1.00000000e+00,   2.00000000e-01,   1.11111111e-01, ...,
         1.00150225e-04,   1.00110121e-04,   1.00070049e-04])

In [17]:
first_array = np.sum(P_array)
first_array

3.0127498564660531

In [ ]:
s_array = np.arange(3,10000,4)
s_array

array([   3,    7,   11, ..., 9991, 9995, 9999])

In [19]:
se_array = 1/s_array
se_array

array([  3.33333333e-01,   1.42857143e-01,   9.09090909e-02, ...,
         1.00090081e-04,   1.00050025e-04,   1.00010001e-04])

In [21]:
sec_array = np.sum(se_array)
sec_array

2.2275017230771077

In [22]:
Pie_array = 4 * (first_array-sec_array)
Pie_array

3.1409925335557816

In [23]:
numerators = np.arange(2,1000001,2)
denoms1 = np.arange(1,1000000,2)
denoms2 = np.arange(3,1000002,2)

In [24]:
fracts1 = numerators/denoms1
fracts2 = numerators/denoms2

In [25]:
prod1 = np.prod(fracts1)
prod2 = np.prod(fracts2)

In [27]:
2 * prod1 * prod2

3.1415910827951143